// <auto-generated />
using System;
using IMS.Plugin.SQLDataStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMS.Plugin.SQLDataStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220407123337_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IMS.CoreBusiness.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "توضیحاتی در مورد دوربین",
                            Name = "دوربین"
                        },
                        new
                        {
                            Id = 2,
                            Description = "توضیحاتی در مورد میکریفون",
                            Name = "میکریفون"
                        },
                        new
                        {
                            Id = 3,
                            Description = "توضیحاتی در مورد مبدل",
                            Name = "مبدل"
                        },
                        new
                        {
                            Id = 4,
                            Description = "توضیحاتی در مورد سه پایه",
                            Name = "سه پایه"
                        });
                });

            modelBuilder.Entity("IMS.CoreBusiness.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quntity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "توضیحات محصول",
                            Name = "دوربین پرتابل",
                            Quntity = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "توضیحات محصول",
                            Name = "دوربین استدیو",
                            Quntity = 3
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "توضیحات محصول",
                            Name = "میکریفون پرتابل",
                            Quntity = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "توضیحات محصول",
                            Name = "کانورتور به HDMI",
                            Quntity = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "توضیحات محصول",
                            Name = "سه پایه پرتابل",
                            Quntity = 15
                        });
                });

            modelBuilder.Entity("IMS.CoreBusiness.Model.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"), 1L, 1);

                    b.Property<int>("BeforeQty")
                        .HasColumnType("int");

                    b.Property<int>("CheckOutQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("LeftInventoryTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProdcutId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecivedProductEmployee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("IMS.CoreBusiness.Model.Product", b =>
                {
                    b.HasOne("IMS.CoreBusiness.Model.Category", "category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("IMS.CoreBusiness.Model.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
